'LineItemsController':
  permission1:
    # Users can only see their own orders
    roles : [user]
    options :
      except : [new, create, render_proof]   
      unless : can_access?  #orders_controller may grant access based on presence of token, etc.